server:
  port: 8003

spring:
  datasource:
    # 这里改成自己的名称
    url: jdbc:mysql://localhost:3306/llmusicplayer?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    #自己的账号密码
    username: root
    password: lh20020123
  redis:
    host: 127.0.0.1
    #    host: 47.108.147.239
    port: 6379
    password:
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
  mail:
    #配置smtp服务主机地址
    # qq邮箱为smtp.qq.com          端口号465或587
    # sina    smtp.sina.cn
    # aliyun  smtp.aliyun.com
    # 163     smtp.163.com       端口号465或994
    host: smtp.163.com
    #发送者邮箱
    username: example@163.com
    #接收者者邮箱
    sendName: example@qq.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: 
    #端口号465或587
    port: 465
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
#    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl